config/routes.rb
Stalltalk::Application.routes.draw do
  devise_for :stalltalkians

  resources :statuses

  resources :checkins

  resources :posts

  root :to => 'home#index'

  resources :stalltalkians

  resources :locations

  resources :poopstations

  match '/logout' => 'user_sessions#destroy'
  match '/poopstations/:id/admin' => 'poopstations#admin'
  match '/stalls/:id/admin' => 'poopstations#admin'
  match '/like/:poopstation/:id' => 'poopstations#like'
  match '/like/:best/:poopstation/:id' => 'poopstations#like'
  match '/poopstations/:id/dash' => 'poopstations#splashscreen'

  match '/stickers' => 'home#generate_stickers'

  match '/best/' => 'posts#bestposts'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if is_mobile_device?
      if not params[:s].nil?
        @poopstation_id = params[:s]
        redirect_to :controller=>'poopstations', :action => 'show', :id => @poopstation_id
      end
    end
  end
  def generate_stickers
    begin
     @count = Stickercount.find_or_create_by_id(1)
     if params["wants_stickers"]["butt_really"] == "true"
      @start = @count
      @start.count = @start.count + 5
      @start.save!
    end
  rescue
  end
  respond_to do |format|
    format.html
    format.json
    format.mobile
  end
end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/generate_stickers.html.erb
      <br>
      <br>
      <br>
      <div class="well">
        <br>
            <% if @start.nil? %>
            <h2> Let's Print Some Stickers! <%= @count.count %> have already been printed worldwide!</h2>
            <br>
            <%= form_tag(stickers_path, :method => "post") do %>
            <%= hidden_field(:wants_stickers, :butt_really, :value => "true") %>
            <%= submit_tag("Generate Fun", :class => "btn btn-primary btn-large") %>
            <% end %>
            <% end %>

            <% if not @start.nil? %>
            <% start = @start.count.to_i - 4 %>
            <% start.to_i.upto(@start.count.to_i) do |i|%>
            Sticker id: <%= (i) %>
            <img src="https://chart.googleapis.com/chart?cht=qr&chs=400x400&chld=H&chl=http://www.stalltalk.info/poopstations/<%= i %>">
            <br>
            <br>
            <% end %>
            <% end %>
    </div>

app/views/home/index.html.erb
<div class="hero-unit">
   <% if flash[:notice] %>
    <div style="margin-top: -100px;" class="alert alert-success alert-block"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:error] %>
    <div style="margin-top: -100px;" class="alert alert-block alert-error"><%= flash[:error] %></div>
    <% end %>
  <div class="wrapper">
    <h1 class="pull-left span9">Start The Movement.</h1>
    <p class="span4 pull-right">
     StallTalk is a toilet-based social network founded by Northwestern Computer Science students and avid toilet users.
     <br><br>
     It allows toileteers to anonymously leave messages at a particular stall. Talking to people is simple. Each stall has a unique QR code that links to a webpage that displays posts at that stall.
     <br><br>
     Users simply scan the code, and -- 'Plop!' -- the rest is history.
   </p>
   <iframe class="promo-vid" width="560" height="315" src="http://www.youtube.com/embed/sudM5TnaPY8" frameborder="0" allowfullscreen></iframe>
   <br><br>
   <a href="/stickers" class="btn btn-inverse btn-large pull-right" style="margin-right: 25px;">Get Stickers</a>
   <a href="/posts" class="btn btn-large btn-primary pull-right" style="margin-right: 25px;">See Posts</a>
 </div>
</div>

<div class="middle-info" id="about">
  <div class="span3 about">
    <h1>The Dream</h1>

    <p>
      We have a dream that one day every toilet around the world will be a beacon of hope. Whether it be through chat or games-- we hope to revolutionize the way people poop.

      <a href="/posts" id="stickers-link" class="btn btn-large btn-primary pull-right">See Posts</a>
    </p>

  </div>
  <div class="span3 about">
    <h1>The [Dream] Team</h1>
    <p>The StallTalk team consists of a group of Northwestern Computer Science students dedicated to living life to the fullest. Our team has a combined 25 years of programming experience, 3 successful companies, and are toilet experts.
    </p>
  </div>
  <div class="span3 about">
    <h1>The Future</h1>

    <p>
      The future of StallTalk is completely decided by you. It is completely open source, and you can checkout the code on <a href="https://github.com/jontonsoup/StallTalk">Github</a>. We have a big goals - some of which include ShatRoulette and ShitterTwitter! Let's get to 50,000 stickers, and Start The Movement!
    </p>

  </div>
</div>
<div class="presentation">
  <div class="mobile-ish">
    <h1>The Mobile App</h2>


      <div class="quotes">
        <h5>A few of our fans...</h5>
        <p>"Captains poop log: stall date 20120501. Discovered an anomaly circling Uranus. Sent a couple of philangies in to investigate. Things got messy and we took heavy losses. The cleanup was a disaster!"</p>
        <br>
        <p>"Weve got a hot number 2 in progress. Be advised it is armed and dangerous. Use extreme force if necessary."</p>
        <br>
        <p>"Do you ever wonder if well ever invent reheatable coffee?"</p>

      </div>

      <%= image_tag 'mobile1.png', :class => 'mobile-image' %>
      <%= image_tag 'mobile2.png', :class => 'mobile-image' %>
    </div>

  </div>

app/views/home/index.mobile.erb
<p>
    <h1>Start The Movement!</h1>
    <br>
    <ul data-role="listview">
        <li>StallTalk is a toilet based social network founded by Northwestern Computer Science students and avid toilet users.</li>
        <li>It allows toileteers to anonymously leave messages at a particular stall.</li>
        <li>Talking to people is simple. Each stall has a unique QR code that links to a webpage that displays posts at that stall.</li>
        <li>Toileteers simply scan the code, and -- 'Plop!' -- the rest is history.</li>
    </p>

    <%= link_to "See all posts!", posts_path, "data-role" => "button" %>

app/views/home/index2.html.erb
      <div id="fb-root"></div>
      <script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));</script>
      <div class="hero-unit">
        <h1>Start The Movement!</h1>
        <br>
        <p>StallTalk is a toilet based social network founded by Northwestern Computer Science students and avid toilet users. It allows toileteers to anonymously leave messages at a particular stall. Talking to people is simple. Each stall has a unique QR code that links to a webpage that displays posts at that stall. Users simply scan the code, and -- 'Plop!' -- the rest is history.</p>
        <%= link_to "Get Stickers".html_safe, stickers_path, :class => "btn  btn-large"%>
        <%= link_to "Support us on IndieGoGo!".html_safe, "http://www.indiegogo.com/stalltalk", :class => "btn btn-large btn-primary"%>
        <%= link_to "Checkout our Video!".html_safe, "http://www.youtube.com/watch?v=mn3aoNhy12M", :class => "btn btn-large"%>
        <br>
        <br>
        <br>
    <div class="fb-like" data-href="http://www.stalltalk.info" data-send="true" data-width="450" data-show-faces="true"></div>

      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="span4">
          <h2>Our Team</h2>
          <p>The StallTalk team consists of a team of Northwestern Computer Science students dedicated to living life to the fullest. Our team has a combined 25 years of programming experience, 3 successful companies, and are toilet experts.</p>
        </div>
        <div class="span4 offset4">
          <h2>Our Dream</h2>
          <p>We have a dream that one day every toilet around the world will be a beacon of hope. Whether it be through chat or games-- we hope to revolutionize the way people poop.</p>
          <p> <%= link_to "See all posts".html_safe, posts_path, :class => "btn btn-primary btn-large"%></p>
        </div>
      </div>
      <hr>
      <div class="row">
        <h2 class="offset4 span4">Our Mobile Application</h2>
      </div>
      <br>
      <div class="row">
        <%= image_tag "stall.png", :class => "thumbnail span3 offset1" %>
        <%= image_tag "all.png", :class => "thumbnail span3 offset3" %>
      </div>