config/routes.rb
Stalltalk::Application.routes.draw do
  devise_for :stalltalkians

  resources :statuses

  resources :checkins

  resources :posts

  root :to => 'home#index'

  resources :stalltalkians

  resources :locations

  resources :poopstations

  match '/logout' => 'user_sessions#destroy'
  match '/poopstations/:id/admin' => 'poopstations#admin'
  match '/stalls/:id/admin' => 'poopstations#admin'
  match '/like/:poopstation/:id' => 'poopstations#like'
  match '/like/:best/:poopstation/:id' => 'poopstations#like'
  match '/poopstations/:id/dash' => 'poopstations#splashscreen'

  match '/stickers' => 'home#generate_stickers'

  match '/best/' => 'posts#bestposts'

end

app/models/checkin.rb
class Checkin < ActiveRecord::Base
  attr_accessible :poopstations_id, :stalltalkian_id, :summary
  belongs_to :poopstations
  belongs_to :stalltalkian
  has_many :statuses
end

app/controllers/checkins_controller.rb
class CheckinsController < ApplicationController
  # GET /checkins
  # GET /checkins.json
  before_filter :authenticate_stalltalkian!
  def index
    @checkins = Checkin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @checkins }
    end
  end

  # GET /checkins/1
  # GET /checkins/1.json
  def show
    @checkin = Checkin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @checkin }
    end
  end

  # GET /checkins/new
  # GET /checkins/new.json
  def new
    @checkin = Checkin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @checkin }
    end
  end

  # GET /checkins/1/edit
  def edit
    @checkin = Checkin.find(params[:id])
  end

  # POST /checkins
  # POST /checkins.json
  def create
    @checkin = Checkin.new(params[:checkin])

    respond_to do |format|
      if @checkin.save
        format.html { redirect_to @checkin, notice: 'Checkin was successfully created.' }
        format.json { render json: @checkin, status: :created, location: @checkin }
      else
        format.html { render action: "new" }
        format.json { render json: @checkin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /checkins/1
  # PUT /checkins/1.json
  def update
    @checkin = Checkin.find(params[:id])

    respond_to do |format|
      if @checkin.update_attributes(params[:checkin])
        format.html { redirect_to @checkin, notice: 'Checkin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @checkin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checkins/1
  # DELETE /checkins/1.json
  def destroy
    @checkin = Checkin.find(params[:id])
    @checkin.destroy

    respond_to do |format|
      format.html { redirect_to checkins_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/checkins_helper.rb
module CheckinsHelper
end

app/views/checkins/_form.html.erb
<%= form_for(@checkin) do |f| %>
  <% if @checkin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@checkin.errors.count, "error") %> prohibited this checkin from being saved:</h2>

      <ul>
      <% @checkin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :poopstation_id %><br />
    <%= f.number_field :poopstation_id %>
  </div>
  <div class="field">
    <%= f.label :summary %><br />
    <%= f.text_field :summary %>
  </div>
  <div class="field">
    <%= f.label :stalltalkian_id %><br />
    <%= f.number_field :stalltalkian_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/checkins/edit.html.erb
<h1>Editing checkin</h1>

<%= render 'form' %>

<%= link_to 'Show', @checkin %> |
<%= link_to 'Back', checkins_path %>

app/views/checkins/index.html.erb
<h1>Listing checkins</h1>

<table class="table table-striped">
  <tr>
    <th>Poopstations</th>
    <th>Summary</th>
    <th>Stalltalkian</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @checkins.each do |checkin| %>
  <tr>
    <td><%= checkin.poopstation_id %></td>
    <td><%= checkin.summary %></td>
    <td><%= checkin.stalltalkian_id %></td>
    <td><%= link_to 'Show', checkin %></td>
    <td><%= link_to 'Edit', edit_checkin_path(checkin) %></td>
    <td><%= link_to 'Destroy', checkin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Checkin', new_checkin_path %>

app/views/checkins/new.html.erb
<h1>New checkin</h1>

<%= render 'form' %>

<%= link_to 'Back', checkins_path %>

app/views/checkins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Poopstations:</b>
  <%= @checkin.poopstation_id %>
</p>

<p>
  <b>Summary:</b>
  <%= @checkin.summary %>
</p>

<p>
  <b>Stalltalkian:</b>
  <%= @checkin.stalltalkian_id %>
</p>


<%= link_to 'Edit', edit_checkin_path(@checkin) %> |
<%= link_to 'Back', checkins_path %>