config/routes.rb
Stalltalk::Application.routes.draw do
  devise_for :stalltalkians

  resources :statuses

  resources :checkins

  resources :posts

  root :to => 'home#index'

  resources :stalltalkians

  resources :locations

  resources :poopstations

  match '/logout' => 'user_sessions#destroy'
  match '/poopstations/:id/admin' => 'poopstations#admin'
  match '/stalls/:id/admin' => 'poopstations#admin'
  match '/like/:poopstation/:id' => 'poopstations#like'
  match '/like/:best/:poopstation/:id' => 'poopstations#like'
  match '/poopstations/:id/dash' => 'poopstations#splashscreen'

  match '/stickers' => 'home#generate_stickers'

  match '/best/' => 'posts#bestposts'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
    user ||= Stalltalkian.new # guest user (not logged in)
    if user.role == "admin"
        can :manage, :all
    elsif user.role == "manager"

    elsif user.role == "servicer"

    end
  end
end

app/models/bathroomobjects.rb
class Bathroomobjects < ActiveRecord::Base
  attr_accessible :name

end

app/models/checkin.rb
class Checkin < ActiveRecord::Base
  attr_accessible :poopstations_id, :stalltalkian_id, :summary
  belongs_to :poopstations
  belongs_to :stalltalkian
  has_many :statuses
end

app/models/location.rb
class Location < ActiveRecord::Base
    has_and_belongs_to_many :poopstations
    has_many :posts
  attr_accessible :category, :city, :name, :state
end

app/models/poopstation.rb
class Poopstation < ActiveRecord::Base
    has_and_belongs_to_many :stalltalkians
    has_and_belongs_to_many :locations
    has_many :posts, :order => "created_at DESC"
    has_many :checkins
  attr_accessible :gender, :stalltalkian_id, :sticker_type
end

app/models/post.rb
class Post < ActiveRecord::Base

    belongs_to :location
    belongs_to :stalltalkian
    belongs_to :poopstation
    validates :text, :presence => true
  attr_accessible :location_id, :poopstation_id, :stalltalkian_id, :text
end

app/models/stalltalkian.rb
require 'bcrypt'
class Stalltalkian < ActiveRecord::Base
  ROLES = %w[manager servicer]
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
    include BCrypt

    has_many :posts
    has_many :checkins
    has_and_belongs_to_many :poopstations
    attr_accessible :email, :name, :password, :role

    public
    def self.hash_password(new_password)
      password = BCrypt::Password.create(new_password)
  end
end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :bathroomobjects_id, :checkin_id, :status
  belongs_to :checkin
  has_one :bathroomobject
end

app/models/stickercount.rb
class Stickercount < ActiveRecord::Base
  attr_accessible :count
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  # attr_accessible :title, :body
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if is_mobile_device?
      if not params[:s].nil?
        @poopstation_id = params[:s]
        redirect_to :controller=>'poopstations', :action => 'show', :id => @poopstation_id
      end
    end
  end
  def generate_stickers
    begin
     @count = Stickercount.find_or_create_by_id(1)
     if params["wants_stickers"]["butt_really"] == "true"
      @start = @count
      @start.count = @start.count + 5
      @start.save!
    end
  rescue
  end
  respond_to do |format|
    format.html
    format.json
    format.mobile
  end
end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.find(:all, :order => "created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.mobile
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.mobile
      format.json { render json: @post }
    end
  end

  def bestposts
    @posts = Post.find(:all, :order => "likes desc")

    respond_to do |format|
      format.html # new.html.erb
      format.mobile
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = self.current_poopstation.post.new

    respond_to do |format|
      format.html # new.html.erb
      format.mobile
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    current_poopstation_id = session[:poopstation_id]
    current_poopstation = Poopstation.find_by_id(current_poopstation_id)
    @post = current_poopstation.posts.new(params[:post])
    respond_to do |format|
      if @post.save
        @texts = @post.text
        current_poopstation.stalltalkians.each do |stalltalkian|
          UserMailer.post_email(@texts, stalltalkian.email, current_poopstation_id, @post.created_at).deliver
        end
        format.html { redirect_to poopstation_url(current_poopstation), notice: 'Thnx for pooping! Come Again.' }
        format.mobile { redirect_to poopstation_url(current_poopstation), notice: 'Thnx for pooping! Come Again.' }
        format.json { render json: @post, status: :created, location: @post }
      else
       format.html { redirect_to poopstation_url(current_poopstation), notice: 'Shit hit the fan!' }
       format.mobile { redirect_to poopstation_url(current_poopstation), notice: 'Shit hit the fan!' }
       format.json { render json: @post, status: :created, location: @post }
     end
   end
 end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.mobile { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.mobile { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.mobile { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkins_helper.rb
module CheckinsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/poopstations_helper.rb
module PoopstationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/stalltalkians_helper.rb
module StalltalkiansHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/_footer.html.erb
<% if request.fullpath == '/' %>
<div class="footer-spread">
	<p class="credits">Design by <a href="http://www.will-wallace.com">wallace</a></p>

	<div class="blocker">

	</div>
	<footer class="foot">
		<% @count = Stickercount.find_or_create_by_id(1) %>
		<span> &copy; StallTalk 1857 | <%= @count.count %> Stickers Served | <a href="mailto:vladamirpoopin@stalltalk.info">Contact Us!</a></span>
	</footer>
</div>
<% end %>

app/views/layouts/_footer.mobile.erb
<div data-role="footer" id="layouts-footer" class="ui-bar" data-type="horizontal">

	<% unless request.fullpath == '/posts' %>
	<h1><%= link_to "See All Posts", posts_path, "data-role" => "button", "data-mini" => "true", "style" => "display: block" %></h1>
	<% end %>
	<h1><a href="mailto:mailto:vladamirpoopin@stalltalk.info" data-role="button" data-mini="true" style="display: block">Suggestions?</a></h1>
	<% if stalltalkian_signed_in?%>
		<h1><%= link_to "Sign Out", destroy_stalltalkian_session_path, "data-role" => "button", "data-mini" => "true", "style" => "display: block", :"data-url"=>"/" %></h1>
	<% else %>
		<h1> <%= link_to "Sign In", "stalltalkians/sign_in", "data-role" => "button", "data-mini" => "true", "style" => "display: block"  %> </h1>
	<% end %>
</div>

app/views/layouts/_header.html.erb
<% if request.fullpath == '/' %>
<div class="head-spread">
  <%= image_tag "logo.jpg", :class => "pull-right", :style => "position:fixed; top: 0px;left: 80%;z-index: 99999"%>
</div>
<% end %>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">StallTalk</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><a href="/">Home</a></li>
          <li><a href="/stickers">Stickers</a></li>
          <li><a href="/posts">Posts</a></li>
          <li><a href="/#about">About</a></li>
          <%#if stalltalkian_signed_in?%>
          <!-- <li> <%# link_to "Sign Out", destroy_stalltalkian_session_path %> </li> -->
          <%# else %>
           <!-- <li> <%#link_to "Sign In", "stalltalkians/sign_in" %> </li> -->
          <%# end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.mobile.erb
<% url = request.path%>
<% if url != root_path %>
<%= link_to "Back", "#", :"data-icon" => "back", :"id" => "layouts-header-back-button", :"data-rel" => "back", :"data-direction" => "reverse", :"data-iconpos" => "right" %>
<% end %>
    <h1 style="font-family: 'Lobster', cursive; font-size: 16pt;">
        <%= @header.nil? ? "StallTalk" : @header %>
    </h1>

<% if url != root_path %>
<%= link_to "Home", root_url, :"data-icon" => :home, :"id" => "layouts-header-home-button", :"data-direction" => "reverse" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StallTalk</title>
  <meta name="google-site-verification" content="3D9gU8nw-aMuVLUO81fDBaU4HcVHOJ028YLrkgNphhA" />
  <%= stylesheet_link_tag    "desktop/application", :media => "all" %>
  <%= javascript_include_tag "desktop/application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%# If we are generating QR codes, make the page blank%>
  <% if @stickers.nil? %>
  <div class="container">
    <%= render 'layouts/header' %>
    <% if flash[:notice] and request.fullpath != "/" %>
    <br>
    <br>
    <div class="alert alert-success alert-block"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:error] and request.fullpath != "/" %>
    <br>
    <br>
    <div class="alert alert-block alert-error"><%= flash[:error] %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
<% else %>
  <%= yield %>
<% end %>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="google-site-verification" content="3D9gU8nw-aMuVLUO81fDBaU4HcVHOJ028YLrkgNphhA" />
  <title>StallTalk!</title>
  <%= stylesheet_link_tag    "mobile/application", :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
  <script type="text/javascript" src="http://code.jquery.com/mobile/1.1.1/jquery.mobile-1.1.1.min.js"></script>
  <%= javascript_include_tag "mobile/application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0," />
  <meta name="apple-mobile-web-app-capable" content="yes" />
</head>
<body>
  <% url = request.path%>
  <% if url == "/stalltalkians/sign_in" %>
    <div data-role="page" id="layouts-page" data-url="/>">
  <% else %>
    <div data-role="page" id="layouts-page" data-url="<%= url %>">
  <% end %>
  <div data-role="header" data-position="fixed">
    <%= render 'layouts/header' %>
  </div>
  <div data-role="content">
   <% if flash[:notice] %>
   <div data-role="navbar">
    <ul>
      <li>
        <a href="" ><%= flash[:notice] %></a>
      </li>
    </ul>
  </div>
  <% end %>
  <% if flash[:error] %>
  <div data-role="navbar">
    <ul>
      <li>
        <a href="" ><%= flash[:error] %></a>
      </li>
    </ul>
  </div>
  <% end %>
  <%= yield %>
</div>
<%= render "layouts/footer" %>
</div>

</body>
</html>